name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      force-release:
        type: boolean

env:
  CARGO_TERM_COLOR: always

permissions:
  id-token: write
  contents: read
  attestations: write

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7
    - run: cargo check --verbose
  build:
    runs-on: ubuntu-latest
    if: github.ref_type == 'tag' || inputs.force-release
    outputs:
      artifact-id: ${{ steps.artifact.outputs.artifact-id }}
      attestation-url: ${{ steps.attest.outputs.attestation-url }}
    steps:
    - uses: actions/checkout@v7
    - run: cargo install cross --git https://github.com/cross-rs/cross
    - run: sudo systemctl start docker
    - run: >
        cross build --verbose --release
        --target x86_64-unknown-linux-gnu
        --target x86_64-pc-windows-gnu
    - uses: actions/upload-artifact@v7
      id: artifact
      with: 
        path: |
          target/**/release/tz.exe
          target/**/release/tz
        if-no-files-found: error
    - uses: actions/attest@v4
      id: attest
      with:
        subject-path: |
          target/**/release/tz.exe
          target/**/release/tz
  release:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref_type == 'tag' || inputs.force-release
    steps:
    - uses: actions/download-artifact@v8
      id: download-artifact
      with:
        artifact-ids: ${{ needs.build.outputs.artifact-id }}
    - name: Release
      uses: softprops/action-gh-release@v3
      with:
        body: Build attested at ${{ needs.build.outputs.attestation-url }}
        files: ${{ steps.download-artifact.outputs }}
